name: Run lint check with clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: './jsonpath.c ./php_jsonpath.h ./src/jsonpath'
          extensions: 'c,h'
          clangFormatVersion: 12
